import useScroll from "@/hooks/useScroll";
import Button, { ButtonStyle } from "@Elements/Button";
import Navbar from "@/components/Fragments/Navbar";
import Head from "next/head";
import * as React from "react";
import vacancy from "../services/vacancy.json";
import ReactPaginate from "react-paginate";
import Link from "next/link";

export default function Home() {
  const jobRef = React.useRef<HTMLElement>(null);
  const scroll = useScroll(jobRef);
  const ITEM_PER_PAGE = 6;
  const [itemsOffset, setItemsOffset] = React.useState(0);
  const endOffset = itemsOffset + ITEM_PER_PAGE;
  const jobVacancy = vacancy.jobs.slice(itemsOffset, endOffset);
  const pageCount = Math.ceil(vacancy.jobs.length / ITEM_PER_PAGE);
  const handlePageClick = ({ selected }: { selected: number }) => {
    const newOffset = (selected * ITEM_PER_PAGE) % vacancy.jobs.length;
    setItemsOffset(newOffset);
  };

  return (
    <>
      <Head>
        <title>Temukan Pekerjaan Impian Anda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="px-[3%] md:px-[10%] mt-10 h-[300px] md:h-[400px] flex items-center">
          <div className="lg:w-[60%]">
            <h1 className="font-bold text-gray-700 text-3xl sm:text-4xl">
              Begabung bersama kami wujudkan mimpi
            </h1>
            <p className="font-medium text-gray-500 text-xl">
              buktikan bahwa anda bisa.
            </p>
            <div
              className="flex flex-wrap gap-3 mt-3
            "
            >
              <Button
                variant={"outline"}
                disabled
                className="hover:opacity-100"
              >
                550+ orang sudah membuktikan
              </Button>
              <Button onClick={() => scroll.inToView()} className="">
                Lowongan Pekerjaan
              </Button>
            </div>
          </div>
        </section>
        <section
          ref={jobRef}
          className="bg-gray-50 px-[3%] md:px-[10%] py-10 mt-10"
        >
          <h1 className="font-bold text-gray-700 text-2xl">Lowongan Kami</h1>
          <p className="text-gray-500">
            Berikut merupakan lowongan - lowongan kerja yang anda dapat
            melamarnya.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 md:gap-3 gap-5 mt-5">
            {jobVacancy.map((job) => {
              return (
                <div
                  key={job.id}
                  className="bg-white md:p-5 p-3 shadow rounded-md flex flex-col md:h-[12rem] h-[9rem]"
                >
                  <h1 className="font-bold text-gray-700 md:text-lg truncate">
                    {job.title}
                  </h1>
                  <p className="text-gray-400 md:text-sm text-xs">{job.type}</p>
                  <p className="font-medium text-gray-500 md:mt-1 text-sm">
                    {job.experience} of experience
                  </p>
                  <div className="mt-auto">
                    <Link
                      className={ButtonStyle()}
                      href={`/lowongan-pekerjaan/${job.slug}`}
                    >
                      Lihat Detail
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
          <ReactPaginate
            pageCount={pageCount}
            onPageChange={handlePageClick}
            containerClassName={"flex mt-10 items-center gap-4"}
            nextClassName="font-medium text-gray-400"
            previousClassName="font-medium text-gray-400"
            pageClassName={
              "w-9 aspect-square flex items-center justify-center text-gray-400"
            }
            activeClassName="bg-white rounded-md shadow-md"
          />
        </section>
      </main>
    </>
  );
}
