import Button from "@Elements/Button";
import Field from "@Elements/Field";
import Head from "next/head";
import * as React from "react";
import { toast } from "react-toastify";
import LoginForm, { LoginValue } from "@Fragments/LoginForm";
import { signIn } from "next-auth/react";
import { GetServerSidePropsContext } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";

export default function LoginPage() {
  const initialValues: LoginValue = {
    email: "",
    password: "",
  };
  return (
    <>
      <Head>
        <title>Masuk akun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginForm
          initialValue={initialValues}
          onSubmit={async (values, formikHelpers) => {
            const response = await signIn("credentials", {
              ...values,
              redirect: false,
            });
            if (response?.ok === false) {
              formikHelpers.setSubmitting(false);
              formikHelpers.resetForm();
              return toast.error("Email atau password salah", {
                autoClose: 600,
                pauseOnHover: false,
              });
            }
            window.location.href = "/profile";
          }}
        >
          {(props) => {
            return (
              <>
                <Field
                  id="email"
                  placeholder="contoh@gmail.com"
                  name="email"
                  label="Alamat Email"
                />
                <Field
                  id="password"
                  placeholder="masukan password kamu"
                  type="password"
                  name="password"
                  label="Password"
                />
                <Button
                  disabled={props.isSubmitting}
                  type="submit"
                  className="w-full"
                >
                  {props.isSubmitting ? "loading..." : "Masuk Sekarang"}
                </Button>
              </>
            );
          }}
        </LoginForm>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(context.req, context.res, authOptions);
  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  return {
    props: {},
  };
}
